### PR TITLE
Fixes #43 http client endpoint metric are not under basename vert.x

### LINKED ISSUE #43: http client endpoint metric are not under basename vert.x
I was testing httpclient endpoint metric using version 3.3.2 

```
            vertxOptions.setMetricsOptions(
                    new DropwizardMetricsOptions()
                            .setEnabled(true)
                            .addMonitoredHttpClientEndpoint(new Match().setValue(".*:.*").setType(MatchType.REGEX))
                            .setJmxEnabled(false)
            );
```

and somehow snapshot didn't give me endpoint metrics in following way 

```
            JsonObject metrics = Deployer.metricsService.getMetricsSnapshot(vertx);
```

so I tried using following way and now it returns. 

```
            JsonObject metrics = Deployer.metricsService.getMetricsSnapshot("http");
```

I was expecting them in "vertx.http.clients.endpoint.<host:port>" somehow they are NOT under basename vertx in registry.

### PR DESCRIPTION
**Pull request by tsegismont**
When client is not named, baseName should still be created with #nameOf

### CODE REVIEW

**Comment by tsegismont** [comment]
@vietj ok to merge? Shall I update the 3.3.3 umbrella?

**Comment by vietj** [comment]
can it be tested ?

**Comment by tsegismont** [comment]
Yep. Will do

2016-08-16 16:20 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by tsegismont** [comment]
Done

2016-08-16 17:07 GMT+02:00 Thomas SEGISMONT <tsegismont@gmail.com>:

**Comment by cescoffier** [comment]
👍

**Pull request merged**
