### PR TITLE
Use the data object generated converter instead of hand-written conversion

### LINKED ISSUE #71: Cannot configure baseName from file
When setting `-Dvertx.metrics.options.configPath`, Vert.x will ignore the `baseName` field. This is also evident in the constructor code:
https://github.com/vert-x3/vertx-dropwizard-metrics/blob/2e37817a00eea1f08bf9a8afb87b239af47e58ac/src/main/java/io/vertx/ext/dropwizard/DropwizardMetricsOptions.java#L121

It doesn't do a `json.getString("baseName")` anywhere in the constructor body.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #71

### CODE REVIEW

**Comment by vietj** [comment]
instead of doing that shouldn't we try to use the data object converter ? I think the json loading code was hand written before the converter generation was done

**Comment by tsegismont** [comment]
@vietj not sure what you mean, this option class does not generate a converter. I thought it was on purpose, wasn't it?

**Comment by vietj** [comment]
I think it did not, if we can use instead a converter, it would be better.

**Comment by tsegismont** [comment]
@vietj done

**Pull request merged**
