### PR TITLE
write additional response metrics for configured server urls

### LINKED ISSUE #79: Collect response codes per configured server url
We have configured some endpoint to be monitored by dropwizard (and grouped by type, e.g. api requets, asset requests). 

```java
  .addMonitoredHttpServerUri(new Match().setValue("/images/.*").setType(MatchType.REGEX).setAlias("image-requests"))
```
We have now nice metrics for how long a request takes. But we can't see how many api requests returned 5xx for example. We only have the overall 5xx count for the whole server. It would be cool to see how many 5xx we have per group (e.g. api requests, asset request) as the overall 5xx rate might be misleading (as asset requests for example can never return 5xx in our case but are done quite a lot in our system).

If you think this feature has some value I can prepare a PR (as I think it is feasible)

### PR DESCRIPTION
**Pull request by atomfrede**
For each configured server url/alias now response metrics are written. e.g `responses-2xx.users`
In particular useful if you monitor different types of request (e.g. api-requests, asset-requests) as currently the whole 5xx response metric does not help much as you don't know which requests are erroneous. Now you can see e.g. its the api request doing errors while the asset request always work. 

closes #79

### CODE REVIEW

**Comment by vietj** [comment]
it looks short and sweet, can you document this ?

**Comment by atomfrede** [comment]
Sure. Will try to do it later today. I guess the best place will we here: https://github.com/vert-x3/vertx-dropwizard-metrics/blob/master/src/main/asciidoc/index.adoc#http-server-metrics

**Comment by vietj** [comment]
totally

**Comment by atomfrede** [comment]
I tried my best, hope that good enough (also fixed a small typo).

**Comment by pendula95** [comment]
resolves #47

**Comment by vietj** [comment]
I will push another patch today that makes lazy loading different relying on Java classloading to make things simpler, is that something you can validate look at today ?

**Pull request merged**
