### PR TITLE
adds extra headers to manifest to help with #178

### PR DESCRIPTION
**Pull request by ANierbeck**

### CODE REVIEW

**Comment by cescoffier** [comment]
With your changes, the bundle can only be used with Spy Fly no ? Can't be make the required capability optional ?

**Comment by ANierbeck** [comment]
it's an official OSGi header ... nothing special about SPI-Fly, Aries SPI-Fly is just one of the possible implementations for the spec. I'll check if it's possible to run the OSGi Bundle without SPI-fly present.

**Comment by ANierbeck** [comment]
in principle a resolution:=optional should be possible on the Require-Capability header, I'm working on changing the pull-request.

**Comment by cescoffier** [comment]
Thanks !

**Pull request merged**
